[[libyyjson]]
arch = "aarch64"
git-tree-sha1 = "49bca4d8a1358c8dbc3eeef96640a8e625c4578a"
libc = "glibc"
os = "linux"

    [[libyyjson.download]]
    sha256 = "8957b48dd21e8fef59cf2b8afd6185c8fab889453259c12699a18d7335e23d61"
    url = "https://github.com/onlang/yyjson_jll.jl/releases/download/libyyjson-v0.8.0+0/libyyjson.v0.8.0.aarch64-linux-gnu.tar.gz"
[[libyyjson]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38aa745bd68032ac96dfe2623b0baa524c3f1617"
libc = "glibc"
os = "linux"

    [[libyyjson.download]]
    sha256 = "7d54d2dcc9081ab875feb3c1b72fa30fe0457aef78aba418ae3be73f55dd8db3"
    url = "https://github.com/onlang/yyjson_jll.jl/releases/download/libyyjson-v0.8.0+0/libyyjson.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[libyyjson]]
arch = "x86_64"
git-tree-sha1 = "81070e35e02b578257dedd540742175c66ea3a4e"
libc = "glibc"
os = "linux"

    [[libyyjson.download]]
    sha256 = "cbf1ed1eb0fd1208c5b61e53af285fbd9f29bb4eae8e0531fe49e3e556b794cf"
    url = "https://github.com/onlang/yyjson_jll.jl/releases/download/libyyjson-v0.8.0+0/libyyjson.v0.8.0.x86_64-linux-gnu.tar.gz"
[[libyyjson]]
arch = "x86_64"
git-tree-sha1 = "91d109167e486efd6e21cb1624a74f46c923c0e3"
os = "windows"

    [[libyyjson.download]]
    sha256 = "54ab0978ae89ce08ad9605d481e320c41bc08ef4ccb137905633cf16601facbf"
    url = "https://github.com/onlang/yyjson_jll.jl/releases/download/libyyjson-v0.8.0+0/libyyjson.v0.8.0.x86_64-w64-mingw32.tar.gz"
